# Generated by Django 2.0.1 on 2018-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_date', models.DateField()),
                ('article_likes', models.IntegerField(default=0)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка')),
            ],
        ),
    ]
