# Generated by Django 2.0.1 on 2018-02-06 20:13

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEnglish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_date', models.DateField()),
                ('article_likes', models.IntegerField(default=0)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoKritika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kritika_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('kritika_text', models.TextField(blank=True, default=None, null=True)),
                ('kritika_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка')),
                ('kritika_video', embed_video.fields.EmbedVideoField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTtailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('trailer_text', models.TextField(blank=True, default=None, null=True)),
                ('trailer_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка')),
                ('trailer_video', embed_video.fields.EmbedVideoField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
