# Generated by Django 2.0.1 on 2018-02-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180206_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoTtailer',
            new_name='VideoTrailer',
        ),
    ]
